swagger: "2.0"
info:
  version: "1.0"
  title: Pier One API
  description: Docker Registry
basePath: /
schemes:
  - https
paths:
  /repositories:
    get:
      summary: List repositories
      operationId: org.zalando.stups.pierone.api/get-repositories
      responses:
        "200":
          description: Return list of repository names
          schema:
            type: array
            items:
              type: string
      produces:
        - application/json
      tags:
        - Pier One API
  /v2/:
    get:
      summary: Check v2
      description: "Endpoint to check for V2(.1) registry API"
      operationId: org.zalando.stups.pierone.api/check-v2
      responses:
        "404":
          description: v2 is not available
      produces:
        - application/json
      tags:
        - Docker API v2
  /v1/search:
    get:
      parameters:
        - name: q
          in: query
          type: string
          description: Search string to match repository names
      responses:
        "200":
          description: Return list of matching repository names
          schema:
            type: object
            properties:
              results:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                
      description: ""
      summary: Search
      operationId: org.zalando.stups.pierone.api/search
      produces:
        - application/json
      tags:
        - Docker API v1
      
  /v1/repositories/{repo1}/{repo2}/tags:
    get:
      parameters:
        - name: repo1
          in: path
          type: string
          required: true
        - name: repo2
          in: path
          type: string
          required: true
      responses:
        "200":
          description: Map of tags to image IDs
        "404":
          description: Repository/tags not found
      description: ""
      summary: Get Tags
      operationId: org.zalando.stups.pierone.api/get-tags
      produces:
        - application/json
      tags:
        - Docker API v1
  /v1/repositories/{repo1}/{repo2}/tags/{tag}:
    put:
      parameters:
        - name: repo1
          in: path
          type: string
          required: true
        - name: repo2
          in: path
          type: string
          required: true
        - name: tag
          in: path
          type: string
          required: true
      responses:
        "200":
          description: Tag was stored successfully
        "409":
          description: Tag already exists
      description: ""
      summary: Put Tag
      operationId: org.zalando.stups.pierone.api/put-tag
      produces:
        - application/json
      tags:
        - Docker API v1
  /v1/repositories/{repo1}/{repo2}/:
    put:
      parameters:
        - name: repo1
          in: path
          type: string
          required: true
        - name: repo2
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified
          headers:
            "X-Docker-Token": 
              type: string
            "X-Docker-Endpoints":
              type: string
          schema:
            type: string
      description: ""
      summary: Put Repo
      operationId: org.zalando.stups.pierone.api/put-repo
      produces:
        - application/json
      tags:
        - Docker API v1
  /v1/repositories/{repo1}/{repo2}/images:
    put:
      parameters:
        - name: repo1
          in: path
          type: string
          required: true
        - name: repo2
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Put Images
      operationId: org.zalando.stups.pierone.api/put-images
      produces:
        - application/json
      tags:
        - Docker API v1
    get:
      parameters:
        - name: repo1
          in: path
          type: string
          required: true
        - name: repo2
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Get Images
      operationId: org.zalando.stups.pierone.api/get-images
      produces:
        - application/json
      tags:
        - Docker API v1
  /v1/images/{image}/json:
    put:
      parameters:
        - name: image
          in: path
          type: string
          required: true
      responses:
        "200":
          description: Image JSON was stored successfully
      description: ""
      summary: Put Image JSON
      operationId: org.zalando.stups.pierone.api/put-image-json
      produces:
        - application/json
      tags:
        - Docker API v1
    get:
      parameters:
        - name: image
          in: path
          type: string
          required: true

      responses:
        "200":
          description: No response was specified
        "404":
          description: Image does not exist
      description: ""
      summary: Get Image JSON
      operationId: org.zalando.stups.pierone.api/get-image-json
      produces:
        - application/json
      tags:
        - Docker API v1
  /v1/images/{image}/layer:
    put:
      parameters:
        - name: image
          in: path
          type: string
          required: true
      responses:
        "200":
          description: Image layer data was stored successfully
      description: ""
      summary: Put Image Layer
      operationId: org.zalando.stups.pierone.api/put-image-layer
      produces:
        - application/json
      tags:
        - Docker API v1
    get:
      parameters:
        - name: image
          in: path
          type: string
          required: true
      responses:
        "200":
          description: Return binary layer data
        "404":
          description: Image layer does not exist
      description: ""
      summary: Get Image Layer
      operationId: org.zalando.stups.pierone.api/get-image-layer
      produces:
        - application/octet-stream
      tags:
        - Docker API v1
  /v1/images/{image}/checksum:
    put:
      parameters:
        - name: image
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Put Image Checksum
      operationId: org.zalando.stups.pierone.api/put-image-checksum
      produces:
        - application/json
      tags:
        - Docker API v1
  /v1/images/{image}/ancestry:
    get:
      parameters:
        - name: image
          in: path
          type: string
          required: true
      responses:
        "200":
          description: Return list of image IDs
          schema:
            type: array
            items:
              type: string
        "404":
          description: Image ID does not exist
      description: ""
      summary: Get Image ancestry
      operationId: org.zalando.stups.pierone.api/get-image-ancestry
      produces:
        - application/json
      tags:
        - Docker API v1
  /v1/_ping:
    get:
      responses:
        "200":
          description: Docker Registry v1 is available
          headers:
            "X-Docker-Registry-Version":
              type: string
          schema:
            type: boolean
      description: ""
      summary: Ping
      operationId: org.zalando.stups.pierone.api/ping
      produces:
        - application/json
      tags:
        - Docker API v1

