swagger: "2.0"

info:
  version: "0.1"
  title: Pier One API
  description: Docker Registry

basePath: /

consumes:
  - application/json
produces:
  - application/json

definitions:
  TagSummary:
    type: object
    properties:
      name:
        type: string
        example: "1.0"
      created:
        type: string
        example: 2015-05-07T15:49:51.230+0200
      created_by:
        type: string
        example: hjacobs

paths:

  ## Docker Registry API v2

  /v2/:
    get:
      summary: check compatibility
      description: Checks for compatibility with Docker Registry v2.
      tags:
        - Docker Registry API v2
      operationId: org.zalando.stups.pierone.api-v2/ping
      responses:
        "404":
          description: v2 is not available

  ## Docker Registry API v1

  /v1/_ping:
    get:
      summary: check compatibility
      description: Checks for compatibility with Docker Registry v1.
      tags:
          - Docker Registry API v1
      operationId: org.zalando.stups.pierone.api-v1/ping
      responses:
        "200":
          description: Docker Registry v1 is available
          headers:
            "X-Docker-Registry-Version":
              type: string
          schema:
            type: boolean

  /v1/search:
    get:
      summary: search repositories
      description: Search for repositories in the registry.
      tags:
        - Docker Registry API v1
      operationId: org.zalando.stups.pierone.api-v1/search
      parameters:
        - name: q
          in: query
          description: Search string to match repository names
          type: string
          required: false
      responses:
        "200":
          description: Return list of matching repository names
          schema:
            type: object
            properties:
              results:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string

  ### Tags

  /v1/repositories/{team}/{artifact}/tags:
    get:
      summary: list tags
      description: Lists all tags of an artifact.
      tags:
        - Docker Registry API v1
      operationId: org.zalando.stups.pierone.api-v1/get-tags
      parameters:
        - name: team
          in: path
          type: string
          required: true
        - name: artifact
          in: path
          type: string
          required: true
      responses:
        "200":
          description: Map of tags to image IDs
        "404":
          description: Repository/tags not found

  /v1/repositories/{team}/{artifact}/tags/{name}:
    put:
      summary: store tag
      description: Stores a tag in the registry for the given artifact.
      tags:
        - Docker Registry API v1
      operationId: org.zalando.stups.pierone.api-v1/put-tag
      parameters:
        - name: team
          in: path
          type: string
          required: true
        - name: artifact
          in: path
          type: string
          required: true
        - name: name
          in: path
          type: string
          required: true
        - name: image
          in: body
          schema:
            description: tag metadata
      responses:
        "200":
          description: Tag was stored successfully
        "409":
          description: Tag already exists

  /v1/repositories/{team}/{artifact}/:
    put:
      summary: dummy
      tags:
        - Docker Registry API v1
      operationId: org.zalando.stups.pierone.api-v1/put-repo
      parameters:
        - name: team
          in: path
          type: string
          required: true
        - name: artifact
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified
          headers:
            "X-Docker-Token":
              type: string
            "X-Docker-Endpoints":
              type: string
          schema:
            type: string

  ### Images

  /v1/repositories/{team}/{artifact}/images:
    put:
      summary: dummy
      tags:
        - Docker Registry API v1
      operationId: org.zalando.stups.pierone.api-v1/put-images
      parameters:
        - name: team
          in: path
          type: string
          required: true
        - name: artifact
          in: path
          type: string
          required: true
      responses:
        "204":
          description: No response was specified

    get:
      summary: dummy
      tags:
        - Docker Registry API v1
      operationId: org.zalando.stups.pierone.api-v1/get-images
      parameters:
        - name: team
          in: path
          type: string
          required: true
        - name: artifact
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified

  /v1/images/{image}/json:
    put:
      summary: store image metadata
      description: Stores the JSON metadata of a Docker image layer.
      tags:
        - Docker Registry API v1
      operationId: org.zalando.stups.pierone.api-v1/put-image-json
      parameters:
        - name: image
          in: path
          type: string
          required: true
        - name: metadata
          in: body
          schema:
            description: image metadata
      responses:
        "200":
          description: Image JSON was stored successfully

    get:
      summary: read image metadata
      description: Reads the JSON metadata of a Docker image layer.
      tags:
        - Docker Registry API v1
      operationId: org.zalando.stups.pierone.api-v1/get-image-json
      parameters:
        - name: image
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified
        "404":
          description: Image does not exist

  /v1/images/{image}/layer:
    put:
      summary: store image binary
      description: Stores the binary data of a Docker image.
      tags:
        - Docker Registry API v1
      operationId: org.zalando.stups.pierone.api-v1/put-image-binary
      consumes:
        - application/octet-stream
      parameters:
        - name: image
          in: path
          type: string
          required: true
        - name: data
          in: body
          schema:
            description: "binary"
      responses:
        "200":
          description: Image layer data was stored successfully

    get:
      summary: read image binary
      description: Reads the binary data of a Docker image.
      tags:
        - Docker Registry API v1
      operationId: org.zalando.stups.pierone.api-v1/get-image-binary
      produces:
        - application/octet-stream
      parameters:
        - name: image
          in: path
          type: string
          required: true
      responses:
        "200":
          description: Return binary layer data
        "404":
          description: Image layer does not exist

  /v1/images/{image}/checksum:
    put:
      summary: check image
      description: Checks an image with a checksum.
      tags:
        - Docker Registry API v1
      operationId: org.zalando.stups.pierone.api-v1/put-image-checksum
      parameters:
        - name: image
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified

  /v1/images/{image}/ancestry:
    get:
      summary: read image ancestry
      description: Returns the whole ancestry for an image.
      tags:
        - Docker Registry API v1
      operationId: org.zalando.stups.pierone.api-v1/get-image-ancestry
      parameters:
        - name: image
          in: path
          type: string
          required: true
      responses:
        "200":
          description: Return list of image IDs
          schema:
            type: array
            items:
              type: string
        "404":
          description: Image ID does not exist

  ## Pier One API

  /teams:
    get:
      summary: list teams
      description: lists all teams that have artifacts
      tags:
        - Pier One API
      operationId: org.zalando.stups.pierone.api/read-teams
      responses:
        "200":
          description: Return list of team IDs
          schema:
            type: array
            items:
              type: string

  /teams/{team}/artifacts:
    get:
      summary: list artifacts
      description: lists all artifacts of a team
      tags:
        - Pier One API
      operationId: org.zalando.stups.pierone.api/read-artifacts
      parameters:
        - name: team
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Return list of artifact IDs
          schema:
            type: array
            items:
              type: string

  /teams/{team}/artifacts/{artifact}/tags:
    get:
      summary: list tags
      description: lists all tags of an artifact
      tags:
        - Pier One API
      operationId: org.zalando.stups.pierone.api/read-tags
      parameters:
        - name: team
          in: path
          required: true
          type: string
        - name: artifact
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Return list of tags
          schema:
            type: array
            items:
              $ref: "#/definitions/TagSummary"

