language: clojure

jdk:
  - oraclejdk8

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'CREATE DATABASE pierone;' -U postgres

script:
  - lein clean
  - lein test

after_script:
  - bash -ex coveralls.sh

notifications:
  email:
    on_failure: change
