swagger: "2.0"
info:
  version: beta
  title: Pier One API
  description: Docker Registry
host: pierone.stups.zalan.do
basePath: /
schemes:
  - https
paths:
  /:
    get:
      summary: Index
      description: "Home page"
      operationId: pierone.core/index
      responses:
        "200":
          description: No response was specified
      produces:
        - application/json
  /v1/search:
    get:
      parameters:
        - name: q
          in: query
          type: string
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Search
      operationId: pierone.core/search
      produces:
        - application/json
  /v1/repositories/{repo1}/{repo2}/tags:
    get:
      parameters:
        - name: repo1
          in: path
          type: string
          required: true
        - name: repo2
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Get Tags
      operationId: pierone.core/get-tags
      produces:
        - application/json
  /v1/repositories/{repo1}/{repo2}/tags/{tag}:
    put:
      parameters:
        - name: repo1
          in: path
          type: string
          required: true
        - name: repo2
          in: path
          type: string
          required: true
        - name: tag
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Put Tag
      operationId: pierone.core/put-tag
      produces:
        - application/json
  /v1/repositories/{repo1}/{repo2}/:
    put:
      parameters:
        - name: repo1
          in: path
          type: string
          required: true
        - name: repo2
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Put Repo
      operationId: pierone.core/put-repo
      produces:
        - application/json

  /v1/repositories/{repo1}/{repo2}/images:
    put:
      parameters:
        - name: repo1
          in: path
          type: string
          required: true
        - name: repo2
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Put Images
      operationId: pierone.core/put-images
      produces:
        - application/json
    get:
      parameters:
        - name: repo1
          in: path
          type: string
          required: true
        - name: repo2
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Get Images
      operationId: pierone.core/get-images
      produces:
        - application/json
  /v1/images/{image}/json:
    put:
      parameters:
        - name: image
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Put Image JSON
      operationId: pierone.core/put-image-json
      produces:
        - application/json
    get:
      parameters:
        - name: image
          in: path
          type: string
          required: true

      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Get Image JSON
      operationId: pierone.core/get-image-json
      produces:
        - application/json
  /v1/images/{image}/layer:
    put:
      parameters:
        - name: image
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Put Image Layer
      operationId: pierone.core/put-image-layer
      produces:
        - application/json
    get:
      parameters:
        - name: image
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Get Image Layer
      operationId: pierone.core/get-image-layer
      produces:
        - application/json
  /v1/images/{image}/checksum:
    put:
      parameters:
        - name: image
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Put Image Checksum
      operationId: pierone.core/put-image-checksum
      produces:
        - application/json
  /v1/images/{image}/ancestry:
    get:
      parameters:
        - name: image
          in: path
          type: string
          required: true
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Get Image ancestry
      operationId: pierone.core/get-image-ancestry
      produces:
        - application/json
  /v1/_ping:
    get:
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Ping
      operationId: pierone.core/ping
      produces:
        - application/json

