swagger: "2.0"
info:
  version: beta
  title: Pier One API
  description: Docker Registry
host: pierone.stups.zalan.do
basePath: /v1
schemes:
  - https
paths:
  /search:
    get:
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Search
      operationId: pierone.core/search
      produces:
        - application/json
  /repositories/{repo1}/{repo2}/tags:
    get:
      parameters:
        - name: repo1
          in: path
        - name: repo2
          in: path
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Get Tags
      operationId: pierone.core/get-tags
      produces:
        - application/json
  /repositories/{repo1}/{repo2}/tags/{tag}:
    put:
      parameters:
        - name: repo1
          in: path
        - name: repo2
          in: path
        - name: tag
          in: path
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Put Tag
      operationId: pierone.core/put-tag
      produces:
        - application/json
  /repositories/{repo1}/{repo2}/:
    put:
      parameters:
        - name: repo1
          in: path
        - name: repo2
          in: path
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Put Repo
      operationId: pierone.core/put-repo
      produces:
        - application/json
  
  /repositories/{repo1}/{repo2}/images:
    put:
      parameters:
        - name: repo1
          in: path
        - name: repo2
          in: path
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Put Images
      operationId: pierone.core/put-images
      produces:
        - application/json
    get:
      parameters:
        - name: repo1
          in: path
        - name: repo2
          in: path
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Get Images
      operationId: pierone.core/get-images
      produces:
        - application/json
  /images/{image}/json:
    put:
      parameters:
        - name: image
          in: path
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Put Image JSON
      operationId: pierone.core/put-image-json
      produces:
        - application/json
    get:
      parameters:
        - name: image
          in: path
      
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Get Image JSON
      operationId: pierone.core/get-image-json
      produces:
        - application/json
  /images/{image}/layer:
    put:
      parameters:
        - name: image
          in: path
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Put Image Layer
      operationId: pierone.core/put-image-layer
      produces:
        - application/json
    get:
      parameters:
        - name: image
          in: path
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Get Image Layer
      operationId: pierone.core/get-image-layer
      produces:
        - application/json
  /images/{image}/checksum:
    put:
      parameters:
        - name: image
          in: path
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Put Image Checksum
      operationId: pierone.core/put-image-checksum
      produces:
        - application/json
  /images/{image}/ancestry:
    get:
      parameters:
        - name: image
          in: path
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Get Image ancestry
      operationId: pierone.core/get-image-ancestry
      produces:
        - application/json
  /_ping:
    get:
      responses:
        "200":
          description: No response was specified
      description: ""
      summary: Ping
      operationId: pierone.core/ping
      produces:
        - application/json

